application: xchange-1132
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app

- url: /update
  script: main.app

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
